###############################################################################
#                                DRUPAL 10                                #
#                            powered by ADMIN                             #
###############################################################################
version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: $CONTAINER_MYSQL
    volumes:
      - ${DB_DUMPS_DIR:-./data/db_dumps}:/tmp/db_dumps
      - ${MYSQL_DIR:-/var/lib/mysql}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PWD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PWD
    ports:
      - "${MYSQL_EXTERNAL_PORT:-3309}:${MYSQL_PORT:-3306}"
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_PHPMYADMIN:-phpmyadmin}
    depends_on:
      - mysql
    ports :
      - "${PHPMYADMIN_PORT:-8082}:80"
    environment:
      PMA_HOST: "$CONTAINER_MYSQL"
    networks:
      - database

  nginx:
    build:
      context: config/docker/nginx
    container_name: ${CONTAINER_NGINX:-nginx}
    working_dir: /application
    environment:
      CONTAINER_PHP_FPM: ${CONTAINER_PHP_FPM:-php-fpm}
    depends_on:
      - php-fpm
    volumes:
      - .:/application
    ports:
      - "${APP_PORT:-8002}:80"
    networks:
      - proxy

  php-fpm:
    build:
      context: config/docker/php-fpm
      args:
        UID: $UID
        GID: $GID
    container_name: ${CONTAINER_PHP_FPM:-php-fpm}
    working_dir: /application
    depends_on:
      - mysql
    volumes:
      - .:/application
      - ${DRUPAL_SITES_DIR:-./sites}:/application/sites
    networks:
      - proxy
      - database

networks:
  proxy:
  database:
